### ISSUE TITLE
ZSTD depends on partial-io but does not have those features

### ISSUE THREAD

**Issue by nemosupremo** [gyscos/zstd-rs#61]
When trying to add zstd to cargo with the tokio feature, every version after 0.4.9 fails with teh following error:

```
error: failed to select a version for `zstd`.
    ... required by package `bacon v0.1.0 (/Users/nemo/rust/bacon)`
versions that meet the requirements `= 0.4.23` are: 0.4.23+zstd.1.4.0

the package `bacon` depends on `zstd`, with features: `partial-io` but `zstd` does not have these features.


failed to select a version for `zstd` which could resolve this conflict
```

```toml
[dependencies]
zstd = { version = "0.4.23+zstd.1.4.0", features = [ "tokio" ] }
```

**Comment by gyscos** [comment]
Hi, and thanks for the request!

I can reproduce the problem, but I'm not sure what's causing it yet. Building with `cargo build --features tokio` works fine from the `zstd-rs` repo, so something may be wrong either with the version on crates.io or with cargo when it pulls the dependency for `bacon`...

**Comment by nemosupremo** [comment]
`bacon` is my own binary I am developing, here's the full cargo.toml

```
[package]
name = "bacon"
version = "0.1.0"
authors = ["Nimi Wariboko Jr. <nimiwaribokoj@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.1"
tokio = "0.1.19"
reqwest = "0.9.15"
tokio-timer = "0.2.10"
tokio-fs = "0.1.6"
zstd = { version = "0.4.23+zstd.1.4.0", features = [ "tokio" ] }
serde = "1.0.90"
serde_json = "1.0.39"
serde_derive = "1.0.90"
failure = "0.1.5"
tokio-io = "0.1.12"
futures = "0.1.26"
```

I [forked the library](https://github.com/nemosupremo/zstd-rs/commit/0922fae246cf02e87ed4b18b930e5e7b949c8d55) and removed the `partial-io` features and that seems to enable the `AsyncWrite` traits for `encoder` - but I'm not sure if this breaks anything else.

**Comment by gyscos** [comment]
It may be caused by having a feature depend on dev dependencies.

I published a new version (0.4.24) where the dev dependencies are no longer optional. Does this help?

**Comment by nemosupremo** [comment]
It builds and it may be fixed - I'm just not expert enough to know for sure (my program still fails to build for unrelated build issues).

FWIW if you use
```
zstd = { version = "^0.4", features = [ "tokio" ] }
```

cargo will use `0.4.9`, which doesn't have `partial-io` features.

**Comment by gyscos** [comment]
I noticed that too earlier, but now it seems to be gone and it correctly fetches 0.4.24.

**Comment by nemosupremo** [comment]
Ok I have compiled a working binary that compressed a file. So this issue can be closed. Only thing I can't seem to figure out is how to properly `finish()` when using combinators.
